### PR TITLE
updating to latest repronim locations/images

### PR DESCRIPTION
**Pull request by satra**
@mih - it would be great if you could check this before i hit merge. 

this is setup to:
1. use the repronim images (which should also be in the VM)
2. download the extra files from this repo.
3. add a configurable option for working dir.
4. set the call format that should work both on my cluster and in the VM. 

i can't actually test on the VM since i can't download it with my current connection and the remote execution is not working well my x2go client.

### CODE REVIEW

**Comment by satra** [comment]
@mih - so i run the above script and it finishes and then i try to repeat the last step and i run into the impossible state error:

```
$ bash fsl_glm_w_amazing_datalad.sh
... # runs to completion
$ cd demo/glm_analysis/
$ datalad run singularity exec -B /tmp --bind /nobackup/scratch/Fri/satra/training/test-exercises/demo/glm_analysis/. -H /nobackup/scratch/Fri/satra/training/test-exercises/demo/glm_analysis/. .datalad/environments/fsl/image feat 'sub-02/1stlvl_design.fsf'
run(impossible): /nobackup/scratch/Fri/satra/training/test-exercises/demo/glm_analysis (dataset) [unsaved modifications present, cannot detect changes by command]
```

**Comment by mih** [comment]
If you ran that script `git status` should reveal the exported bash script as an untracked file. Just `git clean -f` and it should run.

I will later try if `datalad rerun` has the desired effect too.

**Comment by mih** [comment]
I can confirm that a `datalad rerun --since HEAD~3` works as advertised.

Maybe we should set

```
set fmri(overwrite_yn) 1
```

to prevent FSL from adding a '+' directory on rerun. That way people could see straight with Git that nothing changes.

**Comment by satra** [comment]
that might be good for this exercise - we can also use that to show how a mistake in an onset file can be tracked.

**Comment by mih** [comment]
I tried, but FSL insists on renaming the folder :(

**Comment by mih** [comment]
We could revert the analysis output commit and rerun...

**Pull request merged**
